# Dependencies
markdown:	kramdown
highlighter:	pygments

# Setup
title:		Christian's World of Whimsy
tagline:	'Like it says on the tin'
description: > # this means to ignore newlines until "baseurl:"
  A blog for my musings, projects, tinkering and general pondering.
  Feel free to take a look around at some of the stuff I've made,
  I'm pretty proud of it.
url: "http://chrismc92.github.io" # the base hostname & protocol for your site
commentsystem:	disqus
#disqus:		example

#author:
#  name:		'Ian Camporez Brunelli'
#  url:		https://google.com/+IanCamporezBrunelli

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  # - icon:	twitter
  #   url:	https://twitter.com/iancamporez
  #   desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/chrismc92
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://google.com/+ChristianMcNamara
    desc:	Add me on google+

  - icon:	feed
    url:	http://chrismc92.github.io/feed.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	Christian McNamara
  url:		http://chrismc92.github.io
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-sa/4.0/

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics: UA-53948946-1
